# App Name
name: AMOLED

# App Description
description: AMOLED WALLPAPERS

# App Version for both Android & iOS
version: 1.0.0+1

# Dart SDK Version
environment:
  sdk: ">=2.7.0 <3.0.0"

# App Packages from pub.dev for both debug & release mode & for both Android & iOS
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  connectivity: ^0.4.9
  flutter_spinkit: ^4.1.2+1
  shared_preferences: ^0.5.8
  cached_network_image: ^2.2.0+1
  path_provider: ^1.6.11
  esys_flutter_share: ^1.0.2
  permission_handler: ^4.0.0
  file_utils: ^0.1.4
  package_info: ^0.4.1
  fluttertoast: ^7.0.1
  firebase_analytics: ^5.0.16
  # firebase_admob: ^0.9.3+2
  # firebase_crashlytics: ^0.1.3+3
  # firebase_performance: ^0.3.2
  provider: ^4.3.1
  http: ^0.12.2
  fzregex: ^1.0.1
  frazile_algorithm: ^1.0.0
  fztimeago: ^1.0.0
  dio: ^3.0.9
  stripe: ^2.0.4
  razorpay_flutter: ^1.2.1
  in_app_purchase: ^0.3.4+1
  fzwallpaper: ^1.0.2
  stripe_payment: ^1.0.7
  launch_review: ^2.0.0
  transparent_image: ^1.0.0

# App Packages from pub.dev only for debug mode for both Android & iOS
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: "launcher_icon_round"
  ios: true
  image_path: "assets/icon/icon_round.png"

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/

  # Fonts
  fonts:
    # SF Pro Black
    - family: SFProBlack
      fonts:
        - asset: assets/fonts/SF_Pro_Black.otf
    # SF Pro Bold
    - family: SFProBold
      fonts:
        - asset: assets/fonts/SF_Pro_Bold.otf
    # SF Pro Heavy
    - family: SFProHeavy
      fonts:
        - asset: assets/fonts/SF_Pro_Heavy.otf
    # SF Pro Light
    - family: SFProLight
      fonts:
        - asset: assets/fonts/SF_Pro_Light.otf      
    # SF Pro Medium
    - family: SFProMedium
      fonts:
        - asset: assets/fonts/SF_Pro_Medium.otf
    # SF Pro Regular
    - family: SFProRegular
      fonts:
        - asset: assets/fonts/SF_Pro_Regular.otf
    # SF Pro Semi Bold
    - family: SFProSemiBold
      fonts:
        - asset: assets/fonts/SF_Pro_Semibold.otf
    # SF Pro Thin
    - family: SFProThin
      fonts:
        - asset: assets/fonts/SF_Pro_Thin.otf
    # SF Pro Ultra Light
    - family: SFProUltraLight
      fonts:
        - asset: assets/fonts/SF_Pro_Ultralight.otf